version: v0.1
testId: SampleTest
displayName: Sample Test
testPlan: AzureLoadTestGroupOne.jmx
description: Load test website home page Pet Store
engineInstances: 1
subnetId: /subscriptions/abcdef01-2345-6789-0abc-def012345678/resourceGroups/sample-rg/providers/Microsoft.Network/virtualNetworks/load-testing-vnet/subnets/load-testing
configurationFiles:
  - ApacheJMeter.jar
failureCriteria:
  - avg(response_time_ms) > 300
  - percentage(error) > 50
splitAllCSVs: True
certificates:
  - name: my-certificate
    value: https://akv-contoso.vault.azure.net/certificates/MyCertificate/abc1234567890def12345
