# This is a basic workflow 

name: Sample App Deploy

# Controls when the workflow will run
on: 
  workflow_dispatch:

  #push:
      #branches:
         # - main

env: 
  LOAD_TEST_RESOURCE: "petstore01"
  LOAD_TEST_RESOURCE_GROUP: "azureloadtest-rg"
  LOAD_TEST_LOCATION: "East US"

# A workflow run is made of one or more jobs that can run sequentially or in parallel
jobs:

  loadTest:
    name: Load Test

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Actions
        uses: actions/checkout@v3

      - name: Login To Azure
        uses: azure/lohin@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        uses: azure/powershell@v1
        continue-on-error: false
        with:
          inlineScript: |
            az group create --name "${{ env.LOAD_TEST_RESOURCE_GROUP }}" --location "${{ env.LOAD_TEST_LOCATION }}"
          azPSVersion: "latest"

      - name: Create Azure Load Testing Resource
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.LOAD_TEST_RESOUCRE_GROUP }}
          template: ./Test/ARMTemplate/template.json
          parameters: ./Test/ARMTemplate/parameters.json name=${{ env.LOAD_TEST_RESOUCRE }} location="${{ env.LOAD_TEST_LOCATION }}"

      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'Test/config.yml'
          loadTestResource: ${{ env.LOAD_TEST_RESOUCRE }}
          resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}

# Publish Artifacts
  - uses: actions/upload-artifact@v2
    with: 
      name: loadTestResults
      path: ${{ github.workspace }}/loadTest    